import '../styles/globals.css' 
import Head from 'next/head'
import Footer from "../components/Footer"; 
import Nav from "../components/Nav";
import NavMobile from "../components/NavMobile";

import '../styles/nav.css'
import '../styles/hero.css'
import '../styles/projects.css'
import '../styles/services.css'
import '../styles/tech.css'
import '../styles/reviews.css'
import '../styles/footer.css'

import { useMediaQuery } from 'react-responsive';



function MyApp({ Component, pageProps }) {

  const isMobileDevice = useMediaQuery({
    query: "(min-device-width: 0px)",
  });

  const isTabletDevice = useMediaQuery({
    query: "(m-device-width: 768px)",
  });

  const isLaptop = useMediaQuery({
    query: "(min-device-width: 1024px)",
  });

  const isDesktop = useMediaQuery({
    query: "(min-device-width: 1200px)",
  });

  const isBigScreen = useMediaQuery({
    query: "(min-device-width: 1201px )",
  });

  console.log(isDesktop);

  return (
    <>

      <Head>
        <title>Freelance Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
 
      {isMobileDevice &&  <NavMobile />}
      {isDesktop && <Nav />}
    
      <Component {...pageProps} />
      <Footer />
    </>
  )
}

export default MyApp