import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import 'normalize.css';

import styles from '../styles/Home.module.css'
import Nav from "../components/Nav";
import Hero from "../components/Hero";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

  
      <Nav />
      <Hero />

         
         {/* <main className={styles.main}>
            <div className={styles.description}>
              <p>sssssssss ssksks sksks sss</p>
            </div>
  </main> */}
       
    
    </>
  )
}
